name: 自动同步内容至 Farbox
on:
  push:
    branches:
      - master
    paths:
      - '**.md'
      - '**.jade'
      - '**.json'
      - '**.css'
      - '**.py'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "2.x"
      - run: |
          pip install farbox_bucket
          python sync_to_server.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 同步内容至 Farbox
          branch: ${{ github.head_ref }}
